[tool.poetry]
name = "ejercicio_django"
version = "0.1.0"
description = ""
authors = ["Alexander Alc√°zar <aalcazarprogramacion@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^5.2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
